/* eslint-disable max-len */

export const DEALS_FILTER_SETUP_MINUTES_FILTER = 'DEALS_FILTER_CHANGE_MINUTES_FILTER';
export const DEALS_FILTER_SETUP_TEXTS_FILTER = 'DEALS_FILTER_CHANGE_TEXTS_FILTER';
export const DEALS_FILTER_SETUP_DATA_FILTER = 'DEALS_FILTER_CHANGE_DATA_FILTER';

export const DEALS_FILTER_GET_DEALS_REQUEST = 'DEALS_FILTER_GET_DEALS_REQUEST';
export const DEALS_FILTER_GET_DEALS_LOADING = 'DEALS_FILTER_GET_DEALS_LOADING';
export const DEALS_FILTER_GET_DEALS_SUCCESS = 'DEALS_FILTER_GET_DEALS_SUCCESS';
export const DEALS_FILTER_GET_DEALS_FAILURE = 'DEALS_FILTER_GET_DEALS_FAILURE';
